# Generated by Django 4.2.7 on 2025-08-30 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('experience_years', models.IntegerField(verbose_name='Опыт работы (лет)')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, upload_to='masters/', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['sort_order', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Модификатор цены')),
                ('duration_modifier', models.IntegerField(default=0, verbose_name='Модификатор длительности (минуты)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_masterservices', to='masters.master', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_masterservices', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга мастера',
                'verbose_name_plural': 'Услуги мастеров',
                'unique_together': {('master', 'service')},
            },
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', through='masters.MasterService', to='services.service'),
        ),
        migrations.AddField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='masters.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Расписание мастера',
                'verbose_name_plural': 'Расписание мастеров',
                'ordering': ['master', 'day_of_week'],
                'unique_together': {('master', 'day_of_week')},
            },
        ),
    ]
